export enum Turn {
  MY,
  OPPONENT,
}

export const idHandPictures: DynamicObject<string> = {
  1: '../../../../assets/Photoes/card/kobold.png',
  2: '../../../../assets/Photoes/card/sectarian.png',
  3: '../../../../assets/Photoes/card/dwarf.png',
  4: '../../../../assets/Photoes/card/rat.png',
  5: '../../../../assets/Photoes/card/mice.png',
  6: '../../../../assets/Photoes/card/goats.png',
  7: '../../../../assets/Photoes/card/stoneT.png',
  8: '../../../../assets/Photoes/card/lowest.png',
  9: '../../../../assets/Photoes/card/egorka.png',
  10: '../../../../assets/Photoes/card/proud.png',
  11: '../../../../assets/Photoes/card/stoneC.png',
  12: '../../../../assets/Photoes/card/rich.png',
  13: '../../../../assets/Photoes/card/watchman.png',
  14: '../../../../assets/Photoes/card/cannon.png',
  15: '../../../../assets/Photoes/card/wormH.png',
  16: '../../../../assets/Photoes/card/wormF.png',
  17: '../../../../assets/Photoes/card/whipKobold.png',
  18: '../../../../assets/Photoes/card/stone.png',
  19: '../../../../assets/Photoes/card/wormE.png',
  20: '../../../../assets/Photoes/card/medium.png',
  21: '../../../../assets/Photoes/card/leg.png',
  22: '../../../../assets/Photoes/card/ostapL.png',
  23: '../../../../assets/Photoes/card/bladSec.png',
  24: '../../../../assets/Photoes/card/stoneGolem.png',
  25: '../../../../assets/Photoes/card/podserun.png',
  26: '../../../../assets/Photoes/card/mixGolem.png',
  27: '../../../../assets/Photoes/card/golemHead.jpg',
  28: '../../../../assets/Photoes/card/tawernOwner.png',
  29: '../../../../assets/Photoes/card/highest.png',
  30: '../../../../assets/Photoes/card/masterKobold.png',
  31: '../../../../assets/Photoes/card/bladLeader.png',
  32: '../../../../assets/Photoes/card/mouseKing.png',
  33: '../../../../assets/Photoes/card/sigdot.png',
  34: '../../../../assets/Photoes/card/stoneWorm.png',
  35: '../../../../assets/Photoes/card/dwarfGeneral.png',
  36: '../../../../assets/Photoes/card/explKobold.png',
  37: '../../../../assets/Photoes/card/watchmanOld.png',
  38: '../../../../assets/Photoes/card/bigStoneT.png',
  39: '../../../../assets/Photoes/card/strogach.png',
  40: '../../../../assets/Photoes/card/bladMountain.png',
  41: '../../../../assets/Photoes/card/ostapHigh.png',
  42: '../../../../assets/Photoes/card/koboldKing.png',
  43: '../../../../assets/Photoes/card/sproutVan.png',
  44: '../../../../assets/Photoes/card/father.png',
  45: '../../../../assets/Photoes/card/banner.png',
  46: '../../../../assets/Photoes/card/vanomas.png',
  47: '../../../../assets/Photoes/card/golemCreator.png',
  48: '../../../../assets/Photoes/card/egon.png',
  49: '../../../../assets/Photoes/card/arts/collector.jpg'
};

export const idOppHandPictures: DynamicObject<string> = {
  1: '../../../../assets/Photoes/card/back/deck cover red.png',
};

export const idMoneyCollectorPictures: DynamicObject<string> = {
  0: '/',
  1: '../../../../assets/Photoes/card/arts/kobold.jpg',
  2: '../../../../assets/Photoes/card/arts/sectarian.jpg',
  3: '../../../../assets/Photoes/card/arts/dwarf.jpg',
  4: '../../../../assets/Photoes/card/arts/rat.jpg',
  5: '../../../../assets/Photoes/card/arts/mice.jpg',
  6: '../../../../assets/Photoes/card/arts/goats.jpg',
  7: '../../../../assets/Photoes/card/arts/stoneT.jpg',
  8: '../../../../assets/Photoes/card/arts/lowest.jpg',
  9: '../../../../assets/Photoes/card/arts/egorka.jpg',
  10: '../../../../assets/Photoes/card/arts/proud.jpg',
  11: '../../../../assets/Photoes/card/arts/stoneC.jpg',
  12: '../../../../assets/Photoes/card/arts/rich.jpg',
  13: '../../../../assets/Photoes/card/arts/watchman.jpg',
  14: '../../../../assets/Photoes/card/arts/cannon.jpg',
  15: '../../../../assets/Photoes/card/arts/wormH.jpg',
  16: '../../../../assets/Photoes/card/arts/wormF.jpg',
  17: '../../../../assets/Photoes/card/arts/whipKobold.jpg',
  18: '../../../../assets/Photoes/card/arts/stone.jpg',
  19: '../../../../assets/Photoes/card/arts/wormE.jpg',
  20: '../../../../assets/Photoes/card/arts/medium.jpg',
  21: '../../../../assets/Photoes/card/arts/leg.jpg',
  22: '../../../../assets/Photoes/card/arts/ostapL.jpg',
  23: '../../../../assets/Photoes/card/arts/bladSec.jpg',
  24: '../../../../assets/Photoes/card/arts/stoneGolem.jpg',
  25: '../../../../assets/Photoes/card/arts/podserun.jpg',
  26: '../../../../assets/Photoes/card/arts/mixGolem.jpg',
  27: '../../../../assets/Photoes/card/arts/golemHead.jpg',
  28: '../../../../assets/Photoes/card/arts/tawernOwner.jpg',
  29: '../../../../assets/Photoes/card/arts/highest.jpg',
  30: '../../../../assets/Photoes/card/arts/masterKobold.jpg',
  31: '../../../../assets/Photoes/card/arts/bladLeader.jpg',
  32: '../../../../assets/Photoes/card/arts/mouseKing.jpg',
  33: '../../../../assets/Photoes/card/arts/sigdot.jpg',
  34: '../../../../assets/Photoes/card/arts/stoneWorm.jpg',
  35: '../../../../assets/Photoes/card/arts/dwarfGeneral.jpg',
  36: '../../../../assets/Photoes/card/arts/explKobold.jpg',
  37: '../../../../assets/Photoes/card/arts/watchmanOld.jpg',
  38: '../../../../assets/Photoes/card/arts/bigStoneT.jpg',
  39: '../../../../assets/Photoes/card/arts/strogach.jpg',
  40: '../../../../assets/Photoes/card/arts/bladMountain.jpg',
  41: '../../../../assets/Photoes/card/arts/ostapHigh.jpg',
  42: '../../../../assets/Photoes/card/arts/koboldKing.jpg',
  43: '../../../../assets/Photoes/card/arts/sproutVan.jpg',
  44: '../../../../assets/Photoes/card/arts/father.jpg',
  45: '../../../../assets/Photoes/card/arts/banner.jpg',
  46: '../../../../assets/Photoes/card/arts/vanomas.jpg',
  47: '../../../../assets/Photoes/card/arts/golemCreator.jpg',
  48: '../../../../assets/Photoes/card/arts/egon.jpg',
  49: '../../../../assets/Photoes/card/arts/collector.jpg'
};

export interface DynamicObject<T> {
  [key: string]: T;
}

export const field: any[][] = [
  [
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 7,
      health: 11,
      attackSpeed: 16,
      evasion: 0.3,
      moveSpeed: 5,
      cost: 4,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 2,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
];
